OAuthを用いた仮登録
RinachanBoard31/clean-storemap-api pull request #26
Opened 2024-11-09 03:07 UTC by bluecat101

OAuthを用いた仮登録になります。
user-authブランチによって、認証用のURLを発行したので、それに対して認証を入れるgoogleアカウントを選択した際にそのアカウントのemailを用いてuserの登録を行います。
**※仮登録と言っても仮登録用のテーブルは用いず、emailだけでuserを作成します。**

登録後はuserのその他の情報(name,age等)を入力する画面へとリダイレクトします。
その際にurlにidを持たせて、更新時にクライアントからidとuserの情報を送信し、idを用いてどのuserを更新するかを決めます。

2024-11-09 05:56 UTC, tanakenology requested changes
実装ありがとうございます！
私の手元で動かしてみて、 `FRONT_URL/editUser?id=x` にリダイレクトされることを確認しました。

ユーザが Google 認証後に DB に email だけ入ったレコードが登録される（＝仮登録される）と思いますが、現状だと同じユーザのレコードが何個でも登録できてしまいます。なので、同じメアドのユーザは登録できないようにしたいです。

2024-11-13 03:09 UTC, RinachanBoard31 requested changes
実装お疲れ様です！
想像以上にOAuthを導入するために何度もやり取りがあって大変な様子が見受けられましたが、フロント側の実装に向けて処理が書かれており、かつテストもしっかり書かれているところに感動しました😇😇
お疲れ様です(＞人＜;)

emailの存在チェックについて、コメントを確認していただけると幸いです🙇‍♂️
よろしくお願いします！

2024-11-13 03:09 UTC, RinachanBoard31 commented on src/driver/db/user.go
> +	result := DB.Create(&user)
良いですね👍

現状、すでに存在するemailで登録しようとすると、重複して登録されてしまいます。
[こちらのレビュー](https://github.com/RinachanBoard31/clean-storemap-api/pull/26#pullrequestreview-2425228521)にある指摘の通り、Create()するまえに事前にemailの存在チェックを行っていただきたいです！
// 16行目にunique制約が登録されていますが、ローカルで実行した時弾かれますか…？私の環境では弾かれなかったです🤔

既存のemailを確認するロジックを追加する場合、どこに追加すべきか考えてみてください！
個人的には、このCreateUser()の中に実装するのは、"Create"という責務以上のことをやっているので良くないと考えています。
ExistUser()的なメソッドを別で作成して、呼び出し元であるgatewayから、まず存在を確認してからCreateUser()をするという流れの方が良いのかなと考えています。
どのように実装するかはお任せします＞ω＜/

2024-11-13 07:54 UTC, RinachanBoard31 commented
@bluecat101 
ご確認ありがとうございます！
> githubのコメントで画像も載せてありますので参考にしてください。

こちらはどこにあるでしょうか…？
申し訳ないのですが見つけられなかったので、リンクを送っていただけると嬉しいです🙇‍♂️

私の環境で弾かれなかったのは、dockerで立ち上げているdbが前のもので、最新のものがautomigrateされなかったことが原因だと考えます。
もしtanakenologyさんの環境で弾かれているのであれば（tanakenologyさんがApproveされるのであれば）、私の問題ですのでApproveさせていただきます！

@tanakenology 
一点ご相談です。
DB側でunique制約を任せるのは安全上とてもよい仕組みだと思いますが、それのみだと、ビジネスルールとしては重複があるかどうかを気にしないことになります。
現在のbluecat101さんの実装に関する私の疑問点は下記です。
- 本番の実装を考えるのであれば、重複関連でエラーが出るのはCreateUser()の中ですので、DB関連のエラーと同様にエラーコードが500番台になりそうです。しかし、重複しているというのはDB側の問題ではなくユーザ側の問題ですので、400番あたりに分けて実装した方が良いと考えます。また、エラーの内容もDBからのメッセージになるので、ユーザ目線では不親切なものかもしれません。
- 同じユーザが重複して登録されないことは、ビジネスルールの一部だと考えています。その場合は、ソフトウェア側で確認することが必要だと考えます。

私の考えすぎな気がしますが、ユーザの存在確認をコードとして実装すべきかどうかについて、ご意見をいただけないでしょうか(＞人＜;)？

2024-11-13 07:58 UTC, bluecat101 commented
ご確認ありがとうございます。
[こちら](https://github.com/RinachanBoard31/clean-storemap-api/pull/26#discussion_r1839324264)の[RinachanBoard31](https://github.com/RinachanBoard31)のコメントに返信する形で記載しました。

2024-11-13 08:53 UTC, RinachanBoard31 commented
@bluecat101 
何度もすみません、もしかしてですが、コメントのステータスがpendingになっていませんか…？
下書き状態ですと、私たちからは見ることができません(＞人＜;)

2024-11-13 08:59 UTC, RinachanBoard31 commented
私目線では、この先が見えておりません🙇‍♂️
<img width="999" alt="Screenshot 2024-11-13 at 17 58 42" src="https://github.com/user-attachments/assets/61c6cc72-6021-4bef-98db-4f8954e4f95e">

2024-11-13 14:22 UTC, RinachanBoard31 commented on src/driver/db/user.go
> +	result := DB.Create(&user)
@bluecat101 
ありがとうございます！
おかげさまで、確認できました🙇‍♂️

2024-11-13 14:22 UTC, RinachanBoard31 approved these changes

2024-11-16 06:28 UTC, RinachanBoard31 commented on src/usecase/interactor/user.go
> +	}
@bluecat101 
実装ありがとうございます！ご確認が遅くなりすみません(＞人＜;)
実装しているレイヤーや実装内容については、全く問題ないように見えます👍

…ただ、私も混乱してしまっていて、下記をご確認いただきたいです。間違っていたら教えてください🙇‍♂️
- CreateUser()が実行されるのは、エンドポイントが `POST /user`のAPIである。
- しかし、本PRで`GET /auth/signup`（今更ながら、signupやloginのメソッドはPOSTだと思います）が新たに作成された
- `GET /auth/signup`ではgoogleアカウントに紐づいた認証を行い、user tableへの保存まで行う。
- この場合、`POST /user`は混乱を招くので消しちゃってよくて、Exist()をinteractor.SignupDraft()？のCreate()より前で実行すべきだと考える。
- まとめると、現行のCreateUser()は今後使われそうにないので、本PRで新たに実装したSingup系のメソッドと統合して欲しい。その際、デッドコード（実行されなくなるコード）は消していただけると嬉しい。commitは残っているので、復旧はいつでもできます！

すみません、前回のPゼミで聞けばよかった。。。
私の認識は合っているでしょうか…？もしあっていたら、↑のように修正していただきたいです🙇‍♂️

2024-11-16 06:30 UTC, RinachanBoard31 commented on src/usecase/interactor/user.go
> +	}
つまるところ、`POST /auth`を実行して得られたURLを叩いて、user tableに自分のメアドを新規登録しようとしたところ、呼び出されるのがSignupWithAuthだからExist()呼ばれてなくない…？と思った次第です🙇‍♂️

2024-11-16 09:51 UTC, bluecat101 commented on src/usecase/interactor/user.go
> +	}
ご返答ありがとうございます。
その認識であっています。つまり、書く場所間違えています、、すみません。。直します。

ただ、今 POST /user を消すと、webの方でcreateUserが実行できなくなってしまい、エラーのなるので、完全移行までは削除しない方がいいかなと考えていました。
↑この点について消してしまっても良いのであればその点についてご意見いただけると助かります。

2024-11-17 02:01 UTC, RinachanBoard31 commented on src/usecase/interactor/user.go
> +	}
@bluecat101 
ありがとうございます！
失礼しました、それでしたら、一旦残してください🙇‍♂️

2024-11-21 06:56 UTC, tanakenology approved these changes
同一メアドユーザーのレコードが重複して作られないことを確認しました。
LGTM です！

2024-11-21 06:56 UTC, merged