[draft] favorite_storesテーブルにお気に入りのお店情報を保存
RinachanBoard31/clean-storemap-api pull request #29
Opened 2024-11-21 08:20 UTC by RinachanBoard31

2024-11-21 15:56 UTC, bluecat101 requested changes
お疲れ様です。
2点ほど気になった点があったので共有します。そのままでもいい場合もあると思いますが、気になるので一応Request Changeで送らせていただきます。もし変更しないのであれば理由等を聞けたらと思います。🙇

- ExistFavorite()の戻り値について
- FindFavorite()で存在しないときにバックエンド側のログでエラーが出る件について

2024-11-21 15:56 UTC, bluecat101 commented on src/adapter/gateway/store.go
> +		return false, nil
現状常にerrの値がnilになっているので82行目に関してはfalse,errにすべきかと思います。
FindFavorite()で存在しない場合以外(dbにアクセスできない等)のエラーとなって戻ってきた場合に存在しないと扱ってerrが消滅しているのでerrも渡したほうがいいかなと思います。
もしerrを渡さずにnilのまま行くのであれば、ExistFavotite()の戻り値にerrorが不要になるかと思います。
それかtrue,falseで管理せずに"errがない=存在する"として扱ってerrのみを返すのも一手だと思います。

2024-11-21 15:56 UTC, bluecat101 commented on src/driver/db/store.go
> +	err := DB.Where("store_id = ? AND user_id = ?", storeId, userId).First(&store).Error
ここでDBを見た時に存在しない場合にバックエンド側でエラーが発生するかと思います。
存在するかを確認する時に存在しないからといってバックエンド側でエラーがログとして表示されるのは少し違和感がある気がします。🧐必ず存在するとしているものであれば別ですが、、
なので、以下のような感じでFindを使用してバックエンド側でエラーが出ないようにしたほうがいいのかなと思います。
```
result := DB.Where("store_id = ? AND user_id = ?", storeId, userId).Find(&store)
// ture,falseを返す、もしくはエラーを発生させる 
if result.RowsAffected == 0 { // エラー発生バージョン
    return errors.New("favorite store is not found")
}
```

2024-11-21 22:45 UTC, tanakenology reviewed
私の手元で動作確認出来ました！
ひとつコメントしました。残り時間もあるので、修正するかどうかはお任せします！

2024-11-21 22:45 UTC, tanakenology commented on src/driver/router/router.go
> +	router.echo.POST("/stores/favorite", router.storeController.SaveFavoriteStore)
users が複数の favorite_stores を持つので、user_id はパスパラメータにして `/users/:user_id/favorite-stores` とした方が RESTful かなと思ったのですが、どうでしょうか？（もっと早く議論できていたら良かったですね、、）

2024-11-21 22:46 UTC, tanakenology approved these changes

2024-11-22 07:06 UTC, RinachanBoard31 commented on src/adapter/gateway/store.go
> +		return false, nil
@bluecat101 
細かいところまで見ていただきありがとうございます！
.Find()を使う形で修正しました🙇‍♂️

2024-11-22 07:07 UTC, RinachanBoard31 commented on src/driver/router/router.go
> +	router.echo.POST("/stores/favorite", router.storeController.SaveFavoriteStore)
@tanakenology 
ありがとうございます！
バックエンド側のコードのエンドポイントを、`/user/:user_id/favorite-store`に変更しました🙇‍♂️

2024-11-22 07:37 UTC, bluecat101 approved these changes
LGTMです！
対応ありがとうございます！

2024-11-22 07:54 UTC, merged