[back/feat] 直近1週間のお気に入りランキングtop10位のお店を返す
RinachanBoard31/clean-storemap-api pull request #30
Opened 2024-11-21 12:16 UTC by RinachanBoard31

## 本PRでやったこと
- `GET /stores/favorite-ranking`の実装
- 各レイヤーのテストの実装

## 仕様
- 直近1週間・お気に入り登録数が多い順・10件という条件でお店を検索し、json形式で返します
- ランキング一覧ページで叩かれることを想定しています。

## 実行例
- 2店舗に対して、計3件のお気に入り登録がある場合
<img width="748" alt="Screenshot 2024-11-21 at 21 15 02" src="https://github.com/user-attachments/assets/ea297602-0d56-46ae-8b72-a55b2bc5d058">

- 登録数の多いId002から順に返す
<img width="1189" alt="Screenshot 2024-11-21 at 21 04 11" src="https://github.com/user-attachments/assets/dadd7580-98f6-4520-bbf5-ae06ac920a03">

2024-11-21 17:47 UTC, bluecat101 requested changes
お疲れ様です！
データの取得について気になる点が2点ありましたのでご確認よろしくお願いします。

- 取得できるお店は重複しないであっているのか
  - プルリク時に貼っていただいた写真と同じdbの時に実行した時の想定と挙動を下に示します。(上からstore_id順になっています)
    - 想定："Id002","Id001" <= こっちだと思っていました
    - 結果："Id002","Id002","Id001"
  - top10のお店なので重複せずに"Id002","Id001"となるのかなと考えていました。これはどちらを想定していますか？もし重複しないのであれば修正お願いします🙇
- 取得結果の順番はお気に入りの多い順とするのか？
  - 取得結果の想定について取得結果の一番最初のstore(stores[0])が一番お気に入りが多いstoreであるという認識であっていますか？もしこうであれば現状のコードではtop10を探して登録順で取得するコードになっているので、修正の方お願いします。


一応下に僕の環境で起こった事象の写真を載せます。(見えずらくてすみません🙏)
db
<img width="681" alt="image" src="https://github.com/user-attachments/assets/aa1b5a2c-3041-4278-b3a4-99f5ce6b44db">
取得結果
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/d49735fb-6f69-4ad3-8755-04d6bcd4d6ec">
順番が登録順となっている
個人的な想定としては、以下のような形で取得できる想定でした。
<img width="269" alt="image" src="https://github.com/user-attachments/assets/1440eac7-a63a-43be-8f4f-3ac4b9eb20ca">

2024-11-21 17:47 UTC, bluecat101 commented on src/driver/db/store.go
> +	subQuery := DB.Model(&FavoriteStore{}).
この部分の流れ。
1. `subQuery`で１週間のお気に入りランキングtop10に選ばれたstoreを取得する。

2. 作成順のfavorite_storesとsubQueryをjoinしてfavorite_storesの中からsubQueryの条件を満たすものを取得する

2でfavorite_storesの中から取得しているため、順番が作成順であり、重複を気にしないコードになっている。
やり方はいろいろあると思いますが、1の時点でuser_id以外のカラムの情報を全て取得してしまう等でもできるかなと思っています。

2024-11-23 03:27 UTC, RinachanBoard31 commented on src/driver/db/store.go
> +	subQuery := DB.Model(&FavoriteStore{}).
@bluecat101 
ありがとうございます！確かに、要件通りに動いていなかったです。。。
方針として、下記に修正しました。
1. store_idでグループにして、countが多い順に10件だけstore_idを返す。
2. そのstore_idに対してそれぞれ、for文でfavorite_storeを取得する
多い順にstore_id以外のフィールドを持ってくるのはできるのですが、かつ10件だけというのはJOINしている関係で難しく（順番情報がなくなっちゃう）、このように実装しました🙇‍♂️

2024-11-23 03:52 UTC, bluecat101 approved these changes
LGTMです！
ちゃんとランキング順に返ってきました！

**１点だけ**
example/post_stores_favorite.jsonのidはパスパラメータで渡すと思うので削除してしまっていいかと思います。

2024-11-23 04:44 UTC, tanakenology approved these changes
レビュー遅くなってすみません！
動作確認しました！
LGTMです！

2024-11-23 04:55 UTC, merged