userのIDでuuidを使用
RinachanBoard31/clean-storemap-api pull request #33
Opened 2024-11-29 11:45 UTC by bluecat101

2024-12-02 11:53 UTC, tanakenology approved these changes
実装ありがとうございます！
動作は問題なかったです。
一箇所気になったところをコメントしました。確認していただけると幸いです。

2024-12-02 11:53 UTC, tanakenology commented on src/adapter/gateway/user_test.go
> +	})).Return(dbUser, nil)
mock.MatchedBy 初めて見ました。引数の条件をチェックしているんですね。勉強になります。

2024-12-02 11:53 UTC, tanakenology commented on src/adapter/gateway/user_test.go
> +}
ここで uuid の形式をチェックしていますが、 uuid が正しい形式になるかどうかは github.com/google/uuid に依存するので、私たちがテストすることではないと思います。できれば github.com/google/uuid をモックするのが良いと思っています。

2024-12-02 14:51 UTC, bluecat101 commented on src/adapter/gateway/user_test.go
> +}
uuidのテストが周囲の表記とずれすぎるので、とりあえず、uuidのテストを削除して対応しました。🙇

2024-12-03 03:08 UTC, RinachanBoard31 requested changes
@bluecat101 
お疲れ様です！返信がめちゃくちゃ遅れてしまい申し訳ございません。
uuidに変更してくださりありがとうございます！
影響の見えにくい変更ですので、大変でしたよね。。。

1点、エラーになってしまう部分を見つけてしまったため、request changeとさせていただきます🙇‍♂️
修正されたら、またreview requestを送っていただけると嬉しいです(＞人＜;)
よろしくお願いいたします！

2024-12-03 03:08 UTC, RinachanBoard31 commented on src/adapter/controller/user.go
> +	id := c.Param("id")
@bluecat101 
ユーザを新規作成しようとすると、500エラーが発生します🙇‍♂️
![Screenshot 2024-12-03 at 11 55 26](https://github.com/user-attachments/assets/a478182e-0e6c-4d24-8315-c4b991e62e26)

その原因として、この85行目でidに"NaN"(Not a Number)というstringが入ります。
これは、controller/user.goにてUserRequestBodyのIdがint型で定義されているからですね。。。
ここから先、db/user.goにて`FindById(id string)`するときに"NaN"なんてidのユーザはいないよと怒られる感じです。

2024-12-03 03:08 UTC, RinachanBoard31 commented on src/adapter/controller/user_test.go
@bluecat101 
細かい話で恐縮ですが、例えば208行目`TestUpdateUser()`内で作っているdummyのuserIdについても、1ではなく適当なstringを充てておくと誤解が減るかなと思います🙇‍♂️
テストのためのuuidとかは、例えば[このサイト](https://uuid.doratool.com/) で適当に作れます！

2024-12-03 03:17 UTC, RinachanBoard31 approved these changes
@bluecat101 
すみません、フロント側の新しいプルリクを取り込んだらうまく動きました🙇‍♂️
なんでUserRequestBodyのidがintで通るんだ…？パラメータとして必要ないから…？
Approveにさせていただきますが、コメントさせていただいた内容は一度ご確認いただきたいです(＞人＜;)

2024-12-03 04:46 UTC, bluecat101 commented
[こちら](https://github.com/RinachanBoard31/clean-storemap-api/pull/33#discussion_r1866961387)についてUpdateUser()ではUpdateRequestBodyは使用していません(コメントアウトがわかりにくくてすみません🙇。id をパスパラメータに入れていてRequest Body に入れていないので、UserRequestBodyにbindしてもid は取得できないと思います)。

UserRequestBodyはuserを送るときに作ったもので使用しないものは削除しておいた方がよかったですね、、すみません。。(というか、CreateUser()はのちに消えるからUserRequestBody自体が消えるのか？🤔)

2024-12-03 04:47 UTC, bluecat101 commented
@RinachanBoard31 コメントありがとうございます。
[こちら](https://github.com/RinachanBoard31/clean-storemap-api/pull/33#discussion_r1866961387)についてUpdateUser()ではUpdateRequestBodyは使用していません(コメントアウトがわかりにくくてすみません🙇。id をパスパラメータに入れていてRequest Body に入れていないので、UserRequestBodyにbindしてもid は取得できないと思います)。

UserRequestBodyはuserを送るときに作ったもので使用しないものは削除しておいた方がよかったですね、、すみません。。(というか、CreateUser()はのちに消えるからUserRequestBody自体が消えるのか？🤔)

2024-12-03 07:07 UTC, RinachanBoard31 commented
@bluecat101 
了解です！ありがとうございます＞ω＜/
そしたら、UserRequestBody{}からidを消していただくのと、コメントに書かせていただいたTestUpdateUser()関連だけ修正していただき、mergeしていただければと思います🙇‍♂️

2024-12-03 09:31 UTC, merged